// <auto-generated />
using System;
using GestionConvocatorias.Identity.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionConvocatorias.Identity.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811231159_FixPendingModelChanges")]
    partial class FixPendingModelChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Asesoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Calificacion")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocenteAsesorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsesoria")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recomendaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoAsesoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocenteAsesorId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Asesorias");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Avance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaDocumento")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Avances");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Convocatoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorias")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EscalaEvaluacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaLimiteRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPublicacionResultados")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkRubrica")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroEvaluadoresPorProyecto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMaximoIntegrantes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroMaximoProyectos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RubricaAsignada")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaBases")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaConvocatoriaPDF")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaFormatos")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoConvocatoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Convocatorias");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.ConvocatoriaEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConvocatoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ConvocatoriaId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("ConvocatoriaEstudiantes");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocumentoPrevioId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutaUbicacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoPrevioId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalificacionImpactoSocial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalificacionInnovacion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalificacionModeloNegocio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalificacionSustentabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalificacionViabilidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmaElectronica")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacionesGenerales")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PuntajeTotal")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadorId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.EventoCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.InvitacionEvaluador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaAceptacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("InvitacionesEvaluador");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmisorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReceptorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmisorId");

                    b.HasIndex("ReceptorId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaConocimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ConvocatoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DocenteAsesorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvaluadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaTermino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LineaInvestigacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjetivoGeneral")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjetivosEspecificos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Problema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Progreso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCodigoFuente")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaPropuestaPDF")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConvocatoriaId");

                    b.HasIndex("DocenteAsesorId");

                    b.HasIndex("EvaluadorId");

                    b.HasIndex("Folio")
                        .IsUnique();

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.ProyectoEstudiante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RolEnProyecto")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProyectoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("ProyectoEstudiantes");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnosExperiencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AreasEspecializacion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CargoActual")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Certificaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoPersonal")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cuatrimestre")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidades")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("GradoAcademico")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstitucionProcedencia")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineasInvestigacion")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matricula")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modalidad")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profesion")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramaEducativo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PromedioGeneral")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Publicaciones")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCartaCompromiso")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCartaConfidencialidad")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaConstancia")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaCv")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaIdentificacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefonoCelular")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Universidad")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Asesoria", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "DocenteAsesor")
                        .WithMany()
                        .HasForeignKey("DocenteAsesorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocenteAsesor");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Avance", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Proyecto", "Proyecto")
                        .WithMany("Avances")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.ConvocatoriaEstudiante", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Convocatoria", "Convocatoria")
                        .WithMany()
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convocatoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Documento", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Documento", "DocumentoPrevio")
                        .WithMany()
                        .HasForeignKey("DocumentoPrevioId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoPrevio");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Evaluacion", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Proyecto", "Proyecto")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluador");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Mensaje", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Emisor")
                        .WithMany()
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Receptor")
                        .WithMany()
                        .HasForeignKey("ReceptorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Emisor");

                    b.Navigation("Receptor");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Notificacion", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Proyecto", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Convocatoria", "Convocatoria")
                        .WithMany("Proyectos")
                        .HasForeignKey("ConvocatoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "DocenteAsesor")
                        .WithMany()
                        .HasForeignKey("DocenteAsesorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Evaluador")
                        .WithMany()
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Convocatoria");

                    b.Navigation("DocenteAsesor");

                    b.Navigation("Evaluador");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.ProyectoEstudiante", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Proyecto", "Proyecto")
                        .WithMany("Integrantes")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GestionConvocatorias.Identity.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Convocatoria", b =>
                {
                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.Proyecto", b =>
                {
                    b.Navigation("Avances");

                    b.Navigation("Evaluaciones");

                    b.Navigation("Integrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
