// <auto-generated />
using GestionConvocatorias.Identity.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionConvocatorias.Identity.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813000000_AddConvocatoriaConsecutivo")]
    partial class AddConvocatoriaConsecutivo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GestionConvocatorias.Identity.Api.Models.ConvocatoriaConsecutivo", b =>
                {
                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UltimoNumero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Anio");

                    b.ToTable("ConvocatoriaConsecutivos");
                });
#pragma warning restore 612, 618
        }
    }
}
